### PR TITLE
CI: enhancement

### PR DESCRIPTION
**Pull request by SamYuan1990**
- Add no function checks for golang.
- Switch to org internal GHA for kind cluster set up.

Signed-off-by: Sam Yuan <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@rootfs  for kepler operator we use go 1.19, for kepler we use go 1.18 hence, do we have plan to upgrade golang version?

**Comment by rootfs** [comment]
@SamYuan1990 not related to this PR, but do you know why the `Secret source: none` in GHA here? It should be `Secret source: Actions` (see all kepler CI logs)
image

**Comment by SamYuan1990** [comment]
> @SamYuan1990 not related to this PR, but do you know why the `Secret source: none` in GHA here? It should be `Secret source: Actions` (see all kepler CI logs) image

could you please check https://docs.github.com/en/get-started/learning-about-github/access-permissions-on-github? I am not sure but if it's from GHA, it seems default GHA settings?

**Comment by SamYuan1990** [comment]
> @SamYuan1990 not related to this PR, but do you know why the `Secret source: none` in GHA here? It should be `Secret source: Actions` (see all kepler CI logs) image

For example https://github.com/ncipollo/release-action can use default permission settings to create a release page without given a read/write token as secret.

**Review by rootfs — APPROVED** [review]

**Pull request merged**
